### PR TITLE
make zfp test cases work with 4D datasets

### PR DESCRIPTION
**Pull request by swson**
the current test script can work with up to 3D

### CODE REVIEW

**Comment by disheng222** [comment]
It cannot be compiled because of the following errors: 
zfp-zc.c: In function ‘main’:
zfp-zc.c:479:18: error: too many arguments to function ‘ZC_startCmpr’
   dataProperty = ZC_startCmpr(varName, ZC_DOUBLE, (double*)fi, 0, 0, pp, zz, yy, xx);
                  ^~~~~~~~~~~~
In file included from zfp-zc.c:9:0:
/tmp/z-checker-installer/Z-checker/zc-install/include/zc.h:418:18: note: declared here
 ZC_DataProperty* ZC_startCmpr(const char* varName, int dataType, void *oriData, size_t r5, size_t r4, size_t r3, size_t r2, size_t r1);
                  ^~~~~~~~~~~~
zfp-zc.c:481:18: error: too many arguments to function ‘ZC_startCmpr’
   dataProperty = ZC_startCmpr(varName, ZC_FLOAT, (float*)fi, 0, 0, pp, zz, yy, xx);
                  ^~~~~~~~~~~~
In file included from zfp-zc.c:9:0:
/tmp/z-checker-installer/Z-checker/zc-install/include/zc.h:418:18: note: declared here
 ZC_DataProperty* ZC_startCmpr(const char* varName, int dataType, void *oriData, size_t r5, size_t r4, size_t r3, size_t r2, size_t r1);
                  ^~~~~~~~~~~~
In file included from zfp-zc.c:8:0:
zfp-zc.c:555:21: error: ‘zfp_field {aka struct <anonymous>}’ has no member named ‘np’; did you mean ‘nx’?
     np = MAX(field->np, 1u);
                     ^
../include/zfp/macros.h:5:21: note: in definition of macro ‘MAX’
 #define MAX(x, y) ((x) > (y) ? (x) : (y))
                     ^
zfp-zc.c:555:21: error: ‘zfp_field {aka struct <anonymous>}’ has no member named ‘np’; did you mean ‘nx’?
     np = MAX(field->np, 1u);
                     ^
../include/zfp/macros.h:5:33: note: in definition of macro ‘MAX’
 #define MAX(x, y) ((x) > (y) ? (x) : (y))
                                 ^
Makefile:20: recipe for target '../bin/zfp-zc' failed
make: *** [../bin/zfp-zc] Error 1


One reason is Z-checker doesn't support 4D yet. I need to fix it in Z-checker code (https://github.com/CODARcode/Z-checker), but I am not available recently. 
Maybe you want to try it. :)

**Comment by disheng222** [comment]
ZC_startCmpr is a function in Z-checker.

**Comment by swson** [comment]
I think I misused arguments for ZC_startCmpr. Should I close this request and make another one with that fix?

**Comment by disheng222** [comment]
Hi Seung,
I noted you pushed another commit.
Did you try your new version of z-checker-installer to see everything works
fine or not?


Best,
Sheng

**Comment by swson** [comment]
I just tried cloning the latest z-checker-installer and compiling it with the changes I made, and I don't see any error during compilation.

**Comment by disheng222** [comment]
I will check it later. Thanks.

**Comment by disheng222** [comment]
zfp-zc.c has an issue. field->np should be field-nw. I will merge it and then modify it in the master code.

**Pull request merged**
